services:

  slave_db:
    image: postgres:18

    container_name: psql_netology-slave

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test_db
      PGDATA: /var/lib/postgresql/data

    ports:
    - "5436:5432"

    volumes:
    - postgres_data_slave:/var/lib/postgresql/data
    - ./slave-init.sh:/slave-init.sh
     
    command: ["/bin/bash", "/slave-init.sh"]

    networks:
      - pg-network

volumes:
  postgres_data_slave:

networks:
  pg-network:
    external: true